# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

users = User.create({name: "Admin", first_surname: "Administrador", second_surname: "", email: "admin@gmail.com", password: "Admin123", telephone: 123456789, address: "c/hola, 5, 2C, Madrid", role: "admin"}, {name: "Client", first_surname: "Cliente", second_surname: "", email: "client@gmail.com", password: "Client123", telephone: 987654321, address: "c/adios, 2, 4B, Madrid", role: "client"}, {name: "Nuevo", first_surname: "Otro", second_surname: "", email: "nuevo@gmail.com", password: "Nuevo123", telephone: 543216789, address: "c/otra, 8, 1A, Madrid", role: "client"})

authors = Author.create({name: "Ken", first_surname: "Liu", second_surname: "", birth_date: "1976-01-01", nationality: "china"}, {name: "Antoine", first_surname: "de Saint-Exupéry", second_surname: "", birth_date: "1900-06-29", nationality: "francesa"}, {name: "Agatha", first_surname: "Christie", second_surname: "", birth_date: "1890-09-15", nationality: "inglesa"}, {name: "Edgar", first_surname: "Allan", second_surname: "Poe", birth_date: "1809-01-19", nationality: "estadounidense"})

genres = Genre.create({definition: "Filosofía"}, {definition: "Fantasía"}, {definition: "Misterio"}, {definition: "Terror"})

books = Book.create({title: "El zoo de papel", author_id: 1, publication_date: "2017-04-06", n_pages: 544, synopsis: "Quince relatos y novelas cortas de uno de los mejores escritores de ficción breve de la ciencia-ficción.", price: 25}, {title: "Asesinato en el Orient Express", author_id: 3, publication_date: "2018-07-03", n_pages: 240, synopsis: "En un lugar aislado de la antigua Yugoslavia, en plena madrugada, una fuerte tormenta de nieve obstaculiza la línea férrea por donde circula el Orient Express. Procedente de la exótica Estambul, en él viaja el detective Hércules Poirot, que repentinamente se topa con uno de los casos más desconcertantes de su carrera: en el compartimiento vecino ha sido asesinado Samuel E. Ratchett mientras dormía, pese a que ningún indicio trasluce un móvil concreto. Poirot aprovechará la situación para indagar entre los ocupantes del vagón, que a todas luces deberían ser los únicos posibles autores del crimen.", price: 8}, {title: "Muerte en el Nilo", author_id: 3, publication_date: "2019-07-09", n_pages: 352, synopsis: "Un célebre caso que pone a prueba la extrema lucidez de Hércules Poirot. Durante unas placenteras vacaciones en Egipto, el detective Hércules Poirot coincide con Linnet y Simon, unos conocidos suyos que están de luna de miel en el país de los faraones. El encanto de tan maravillosos días se rompe cuando una mañana, en el transcurso de un crucero por el Nilo, la bella Linnet aparece muerta de un disparo en la cabeza. ¿Será capaz Poirot de encontrar al asesino de la joven esposa? ¿Será capaz de discernir entre imaginación y realidad, aun estando a bordo la ex pareja de Simon, empeñada desde el mismo día de la boda en arruinar su matrimonio con la desafortunada Linnet? El misterio está servido.", price: 8}, {title: "El principito", author:id: 2, publication_date: "2001-09-01", n_pages: 96, synopsis: "Fábula mítica y relato filosófico que interroga acerca de la relación del ser humano con su prójimo y con el mundo, El Principito concentra, con maravillosa simplicidad, la constante reflexión de Saint-Exupery sobre la amistad, el amor, la responsabilidad y el sentido de la vida.", price: 12}, {title: "Cuentos", author_id: 4, publication_date: "2019-01-24", n_pages: 888, synopsis: "Casi siempre ignorado por sus contemporáneos, el genio atormentado de Edgar Allan Poe no tardó en ser reconoícido tras su muerte por autores de la talla de Baudelaire, Dostoievski, Jules Verne o Mallarme. En la actualidad, sus cuentos son considerados como perfectas obras pioneras del terror psicológico y tambien de otros generos como la narración detectivesca o la ciencia ficción. Además de recopilar todos sus relatos breves, este volumen se abre con una completa introducción al universo teneíbroso y oscuro de Poe, y presenta la celebre traducción de otro maestro del cuento: Julio Cortázar.", price: 20})
